name: recall
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  agora_rtc_engine: 0.9.4
  permission_handler: ^3.0.0
  #网络请求
  dio: 2.1.3  
  #json解析
  json_serializable: 2.2.2
  #数据持久化
  shared_preferences: 0.5.2
  
  # local_notifications: 0.0.7
  #websocket
  socket_io_client: ^0.9.3

  # adhara_socket_io: 0.1.10
  #上拉下拉刷新控件
  flutter_easyrefresh: ^1.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
  - assets/images/match.gif
  - assets/images/hardon.jpg
